### ISSUE TITLE
documentation: unclear role of modules.rst

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/mini-kep#97]
As of now in documentation I have an issue with modules.rst file. In runtime I get an error message:
```
\mini-kep\doc\rst\modules.rst:: WARNING: document isn't included in any toctree
```
I'm not understanding why modules.rst needed at all? It this a default file to insert to index.rst? 

@aptiko, are you familiar with this? @dz0 ?

**Comment by aptiko** [comment]
Apparently when you originally created the sphinx documentation you also somehow created `modules.rst` yourself—it doesn't seem sphinx is creating it itself.

I'm closing this issue since you moved the file to `issues/adandonded`. (We can cleanup `issues/adandoned` when we're done fixing sphinx.) If I'm wrong please reopen.

**Comment by epogrebnyak** [comment]
```modules.rst``` is created by ```sphinx-apidoc``` unless ```--no-toc``` key is supplied. It seems it is a default output of  ```sphinx-apidoc```, so I wanted to know what is the usual role of ```modules.rst``` in a project. To me is seems like a prototype for index.rst. 

I generate rst's with ```--no-toc``` now, ```modules.rst``` is not created and we can lean leave the issue closed as it is not affecting the documentation now.

**Comment by epogrebnyak** [comment]
> We can cleanup issues/adandoned when we're done fixing sphinx.

There is a lot more there, let it hang there until some kind of 'release', lets cleanup then.
